spring.application.name=estacionamento

# 26/08/2026

# Aplicação conversando com o banco de dados
spring.datasource.url=jdbc:h2:file:./database/appdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# http://localhost:8080/h2-console